CREATE TABLE User (
 MemberID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Password VARCHAR(100) NOT NULL CHECK (LENGTH(Password) >= 8),
 Interests TEXT,
 TotalKMTravelled INT DEFAULT 0);

CREATE TABLE Admin (
 AdminID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(50) NOT NULL,
 Password VARCHAR(100) NOT NULL CHECK (LENGTH(Password) >= 8));

CREATE TABLE Country (
 CountryID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL);

CREATE TABLE City (
 CityID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Coordinates VARCHAR(100),
 CountryID INT NOT NULL,
 FOREIGN KEY (CountryID) REFERENCES Country(CountryID) ON DELETE CASCADE);

CREATE TABLE Location (
 LocationID INT AUTO_INCREMENT PRIMARY KEY,
 Name VARCHAR(100) NOT NULL,
 Description TEXT,
 Coordinates VARCHAR(100),
 OverallRating DECIMAL(3, 2),
 CityID INT NOT NULL,
 FOREIGN KEY (CityID) REFERENCES City(CityID) ON DELETE CASCADE);

CREATE TABLE Post (
 PostID INT AUTO_INCREMENT PRIMARY KEY,
 Title VARCHAR(200) NOT NULL,
 Text TEXT,
 Media TEXT,
 IsUnderReview BOOLEAN DEFAULT TRUE,
 Rating DECIMAL(3, 2),
 Date DATE NOT NULL,
 MemberID INT NOT NULL,
 AdminID INT,
 FOREIGN KEY (MemberID) REFERENCES User(MemberID) ON DELETE CASCADE,
 FOREIGN KEY (AdminID) REFERENCES Admin(AdminID) ON DELETE SET NULL);

CREATE TABLE TravelLog (
 MemberID INT NOT NULL,
 CityID INT NOT NULL,
 DurationOfStay INT,
 Date DATE,
 PRIMARY KEY (MemberID, CityID),
 FOREIGN KEY (MemberID) REFERENCES User(MemberID) ON DELETE CASCADE,
 FOREIGN KEY (CityID) REFERENCES City(CityID) ON DELETE CASCADE);

CREATE TABLE Comment (
 CommentID INT AUTO_INCREMENT PRIMARY KEY,
 PostID INT NOT NULL,
 MemberID INT NOT NULL,
 Text TEXT NOT NULL,
 Media TEXT,
 Date DATE NOT NULL,
 Rating DECIMAL(3, 2),
 FOREIGN KEY (PostID) REFERENCES Post(PostID) ON DELETE CASCADE,
 FOREIGN KEY (MemberID) REFERENCES User(MemberID) ON DELETE CASCADE);

CREATE TABLE GroupTable (
 GroupName VARCHAR(100) PRIMARY KEY,
 Description TEXT,
 Tags TEXT);

CREATE TABLE GroupMembers (
 GroupName VARCHAR(100) NOT NULL,
 MemberID INT NOT NULL,
 IsModerator BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (GroupName, MemberID),
 FOREIGN KEY (GroupName) REFERENCES GroupTable(GroupName) ON DELETE
CASCADE,
 FOREIGN KEY (MemberID) REFERENCES User(MemberID) ON DELETE CASCADE);

CREATE TABLE DiscussionPost (
 PostID INT NOT NULL,
 GroupName VARCHAR(100) NOT NULL,
 IsPinned BOOLEAN DEFAULT FALSE,
 PRIMARY KEY (PostID, GroupName),
 FOREIGN KEY (PostID) REFERENCES Post(PostID) ON DELETE CASCADE,
 FOREIGN KEY (GroupName) REFERENCES GroupTable(GroupName) ON DELETE
CASCADE);

CREATE TABLE CityGuide (
 PostID INT NOT NULL,
 CityID INT NOT NULL,
 VisitDuration INT,
 ActivityTypes TEXT,
 RatingOutOf10 INT CHECK (RatingOutOf10 BETWEEN 1 AND 10),
 KeyPoints TEXT,
 Tags TEXT,
 PRIMARY KEY (PostID, CityID),
 FOREIGN KEY (PostID) REFERENCES Post(PostID) ON DELETE CASCADE,
 FOREIGN KEY (CityID) REFERENCES City(CityID) ON DELETE CASCADE);

CREATE TABLE LocationReview (
 PostID INT NOT NULL,
 LocationID INT NOT NULL,
 PRIMARY KEY (PostID, LocationID),
 FOREIGN KEY (PostID) REFERENCES Post(PostID) ON DELETE CASCADE,
 FOREIGN KEY (LocationID) REFERENCES Location(LocationID) ON DELETE CASCADE);

CREATE TABLE TopSpotsList (
 CityID INT NOT NULL,
 AdminID INT NOT NULL,
 Date DATE,
 PRIMARY KEY (CityID),
 FOREIGN KEY (CityID) REFERENCES City(CityID) ON DELETE CASCADE,
 FOREIGN KEY (AdminID) REFERENCES Admin(AdminID) ON DELETE CASCADE);